### ISSUE TITLE
Provide stable version for composer

### ISSUE THREAD

**Issue by Doka-NT** [bupy7/yii2-ajaxfilter#1]
Hello!
Can you provide a stable release version at packagist.org for your package? 
I think it's bad practice to specify package as **"package": "dev-master"** in composer.json

**Comment by bupy7** [comment]
Hi. The stable version since 2 Jun 2015 https://github.com/bupy7/yii2-ajaxfilter/tree/v1.0.0

**Comment by Doka-NT** [comment]
I talk about packagist.org 
There is no stable version 
https://packagist.org/packages/bupy7/yii2-ajaxfilter

**Comment by bupy7** [comment]
I shall be fixing this. Thx!
